# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  鸟不拉屎
subtitle: 人生有几个十年呢？点点滴滴，用文字记录
name: 鸟不拉屎
email: hulang6666@qq.com
description: 本站是鸟不拉屎的技术分享博客。内容涵盖生活故事、Java后端技术、Spring Boot、Spring Cloud、微服务架构、高可用架构、中间件使用、系统监控等相关的研究与知识分享。
keywords: niaobulashi,鸟不拉屎,Spring,Spring Boot,Spring Cloud,MongoDB,Jvm,Docker,生活故事,架构,大数据,一线,FastDFS,开发者,编程,代码,开源,IT网站,Developer,Programmer,Coder,Geek,IT技术博客,Java,Python,
encoding: "utf-8"
favicon: favicon.ico

repository: niaobulashi/niaobulashi.github.io
github_url: https://github.com/niaobulashi
url: https://niaobulashi.github.io
enforce_ssl: niaobulashi.com
personal_blog_url: https://niaobulashi.com

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-octicons

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
  coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:

  -
    href: https://niaobulashi.com
    label: 个人博客
    target: _blank

  -
    href: /gitchat.html
    label: Chat
    target: _self

  -
    href: https://www.cnblogs.com/niaobulashi
    label: 博客园
    target: _blank

  -
    href: /life.html
    label: 故事
    target: _self

  -
    href: /arch.html
    label: 架构
    target: _self

  -
    href: /link.html
    label: 友链
    target: _self



# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source
    target: _self

  -
    href: /spring-boot.html
    label: Spring Boot
    target: _self
    subnav:

      -
        subHref: /spring-boot.html
        subLabel: Spring Boot

      -
        subHref: /spring-cloud.html
        subLabel: Spring Cloud

  -
    href: /java.html
    label: Java
    target: _self

  -
    href: /archives.html
    label: Archives
    target: _self

  -
    href: /about.html
    label: About
    target: _self


# labels. my blog key words
labels:

  -
    href: /mybatis.html
    label: mybatis
    target: _self

  -
    href: /payment.html
    label: 支付
    target: _self

  -
    href: /fastdfs.html
    label: FastDFS
    target: _self

  -
    href: /mongodb.html
    label: MongoDB
    target: _self

  -
    href: /docker.html
    label: Docker
    target: _self

  -
    href: /it.html
    label: IT
    target: _self

  -
    href: /python.html
    label: Python
    target: _self


# selected articles
classes:

  -
    href: /life.html
    name: 我的故事
    describe: 生活就是故事，故事就是生活

  -
    href: /arch.html
    name: 架构师之路
    describe: 一个架构师的自我修养

  -
    href: /java.html
    name: Java 系列文章
    describe: Java 之根基，Java 程序员必学


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
   username: niaobulashi
# https://imsun.net/posts/gitment-introduction/
gitment:
   owner: niaobulashi
   repo: niaobulashi.github.io
   oauth:
       client_id: 2bbd0153436b8c2f1c0b
       client_secret: 71e07a7e992584e013aa3e29d7e9f993b58bf295
 #https://github.com/gitalk/gitalk#install
gitalk:
  owner: niaobulashi
  repo: niaobulashi.github.io
  clientID: 1a212e3a9a8213a6d5c2
  clientSecret: 90ff370b6828c99d88115aa3a81a4c6fe8618822
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Spring Boot, Spring Cloud, Redis, Struct, Hibernet, MyBatis]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, VueJS, LayUI, Boostrap]
skill_mobile_app_keywords: [Flutter]
